{{=[[ ]]=}}

<div id="top-bars" >

    [[#camaleao.tabs.bar.useUOL.value ]]

        <div class="barrauol-bg full">
            <script type="text/javascript" src="https://sac.uol.com.br/info/sac/default/js/uol.js" ></script>
            <script type="text/javascript">
                try{
                  writeUOLBar();
                }catch(e){
                  console.log("A barra UOL nao foi carregada com sucesso.", e);
                }
            </script>
        </div>

    [[/camaleao.tabs.bar.useUOL.value]]



    [[#camaleao.tabs.bar.useBOL.value ]]
        <div class="barrauol-bg full" >
            <script type="text/javascript" src="https://simg.uol.com.br/interacao/wor/bol/barra-v3.js" charset="ISO-8859-1" ></script>
        </div>
    [[/camaleao.tabs.bar.useBOL.value]]

</div>
