    {{=[[ ]]=}}
    [[#camaleao.tabs.resources.css.values]]
    <link rel="stylesheet" [[camaleao.tabs.advanced.hrefString.value]]"[[.]]" />
    [[/camaleao.tabs.resources.css.values]]

    [[#camaleao.tabs.resources.jsHead.values]]
    <script type="text/javascript" [[camaleao.tabs.advanced.srcString.value]]"[[.]]" ></script>
    [[/camaleao.tabs.resources.jsHead.values]]

    <script type="text/javascript" [[camaleao.tabs.advanced.srcString.value]]"[[camaleao.tabs.resources.fixturesDir.value]]fixtures.js?cacheSlayer=<!--#config timefmt="%j%H%M%S" --><!--#echo var='DATE_LOCAL' -->"></script>

    <script type="text/javascript" src="https://jsuol.com.br/bk/validation/v0.0.20/validation-all.js?cacheSlayer=<!--#config timefmt="%j%H%M%S" --><!--#echo var='DATE_LOCAL' -->"></script>
