    {{=[[ ]]=}}
    [[#camaleao.tabs.resources.jsFooter.values]]
    <script type="text/javascript" [[camaleao.tabs.advanced.srcString.value]]"[[.]]"></script>
    [[/camaleao.tabs.resources.jsFooter.values]]


    [[#camaleao.tabs.resources.metrics.values]]
    <script type="text/javascript" [[camaleao.tabs.advanced.srcString.value]]"[[.]]"></script>
    [[/camaleao.tabs.resources.metrics.values]]
