    {{=[[ ]]=}}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="[[camaleao.tabs.head.metatagDescription.value]]">
    <meta name="google-site-verification" content="[[camaleao.tabs.head.metatagVerification.value]]" />
    <meta property="og:url" content="https://sac.uol.com.br/"/>
    <meta property="og:title" content="[[camaleao.tabs.head.title.value]]" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="[[camaleao.tabs.head.ogImage.value]]" />
    <meta property="og:image:secure_url" content="[[camaleao.tabs.head.ogImageSecure.value]]" />
    <meta property="og:site_name" content="[[camaleao.tabs.head.ogSiteName.value]]" />
    <meta property="og:description" content="[[camaleao.tabs.head.metatagDescription.value]]"/>

    <!-- For desktop browsers -->
    <link rel='SHORTCUT ICON' href='[[camaleao.tabs.resources.faviconDir.value]]favicon.ico' />

    <!-- For iPhone 6 Plus with @3× display: -->
    <link rel="apple-touch-icon-precomposed" sizes="180x180" href="[[camaleao.tabs.resources.faviconDir.value]]apple-touch-icon-180x180-precomposed.png">

    <!-- For iPad with @2× display running iOS ≥ 7: -->
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="[[camaleao.tabs.resources.faviconDir.value]]apple-touch-icon-152x152-precomposed.png">

    <!-- For iPad with @2× display running iOS ≤ 6: -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="[[camaleao.tabs.resources.faviconDir.value]]apple-touch-icon-144x144-precomposed.png">

    <!-- For iPhone with @2× display running iOS ≥ 7: -->
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="[[camaleao.tabs.resources.faviconDir.value]]apple-touch-icon-120x120-precomposed.png">

    <!-- For iPhone with @2× display running iOS ≤ 6: -->
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="[[camaleao.tabs.resources.faviconDir.value]]apple-touch-icon-114x114-precomposed.png">

    <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≥ 7: -->
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="[[camaleao.tabs.resources.faviconDir.value]]apple-touch-icon-76x76-precomposed.png">

    <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≤ 6: -->
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="[[camaleao.tabs.resources.faviconDir.value]]apple-touch-icon-72x72-precomposed.png">

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: --><!-- 57×57px -->
    <link rel="apple-touch-icon-precomposed" href="[[camaleao.tabs.resources.faviconDir.value]]apple-touch-icon-precomposed.png">

